### ISSUE TITLE
No user VBL or framecounter in 1.3?

### ISSUE THREAD

**Issue by torkildl** [arnaud-carre/ldos#4]
Checking out the exciting new version of LDOS today, and I realized that the interface now does not offer the global framecounter nor the user-specified VBL callback. These were very useful features IMHO. 

In kernel.asm it seems the user callback and SVAR_VBL_COUNT is still there, but there is no place in the jumptable to install one or get the frame count.
 
Are these gone for good?

**Comment by arnaud-carre** [comment]
you're right it's a bit confusing. The counter is now synced with 50hz music driver tick. You can get it using LDOS_MUSIC_GET_TICK.
But I just figure out it's incremented only if you have music. I'll add a global counter too.

**Comment by torkildl** [comment]
Aha! Is the counter reset if a new module Is loaded/started? A global counter is useful!

**Comment by arnaud-carre** [comment]
yes right now LDOS_MUSIC_GET_TICK counter is reset to 0 when you start the music. I'm adding a global counter also right now :) online soon

**Comment by arnaud-carre** [comment]
LDOS_GET_CLOCK_TICK , done :)

**Comment by torkildl** [comment]
Awesome! :)

**Comment by arnaud-carre** [comment]
btw I just figured out I did a bug adding global clock tick. This clock was already incremented by trackloader so incremented by 2 each tick. I just pushed a fix

**Comment by torkildl** [comment]
Good to hear!

What about the user VBL callback, will it be reinstalled? It is not in the kernel jumptable anymore, but the code is still in the kernel.

**Comment by arnaud-carre** [comment]
have to check that, I want to get rid of it. ( I want everything "VBL" synced to be on user side only ). The only reason I keep the VBL right now is just the fade-to-black at boot time... :)

**Comment by torkildl** [comment]
Ok, so I will prepare for no LDOS VBL then! :)

Another thing: the installer now lists all files as "tmpSrc.bin" in the output... :-)

**Comment by arnaud-carre** [comment]
oh that's unfortunate! I'll do a fix for that.
Btw I'm interested to know: is the VBL removal an issue for you? to me all user fx use their own VBL or Copper interrupt handler. But maybe I'm wrong. What's your typical use case for this LDOS VBL irq handler?

**Comment by torkildl** [comment]
Thanks! 

I don't mind doing my own interrupts (even though I always hated them back in the days). There's no real need for one, and gives more control to be able to cut out the VERTB interrupt.

I am doing a demo now, and have used the callback feature a couple of places, but I can happily switch to setting my own interrupts. :-)

**Comment by torkildl** [comment]
Btw,  I am very happy to see LSP included. Actually I just now tested a modeule that P61 had serious problems with, but LSP handled it perfectly. Looking forward to use it!

**Comment by arnaud-carre** [comment]
glad you like LSP. My main concern about p61 was that the converter is amiga only and it's pretty hard to use on windows platform. LSP is suited with the windows LDOS toolchain

**Comment by arnaud-carre** [comment]
> Ok, so I will prepare for no LDOS VBL then! :)
> 
> Another thing: the installer now lists all files as "tmpSrc.bin" in the output... :-)

I just tested and that's not what I see when building the sample demo.
![image](https://user-images.githubusercontent.com/12719901/144916589-e4b01895-d53c-4c5e-bcd2-ba9ab0e55171.png)

**Comment by torkildl** [comment]
Ok, I see I was unxlear.  I meant the lines under 'loading'. Above and at the end they are listed with their names. Sorry!Sendt fra min Galaxy
-------- Opprinnelig melding --------Fra: Arnaud Carré ***@***.***> Dato: 06.12.2021  21:21  (GMT+01:00) Til: arnaud-carre/ldos ***@***.***> Ko: "Torkild H. Lyngstad" ***@***.***>, Author ***@***.***> Emne: Re: [arnaud-carre/ldos] No user VBL or framecounter in 1.3? (Issue #4) 

Ok, so I will prepare for no LDOS VBL then! :)
Another thing: the installer now lists all files as "tmpSrc.bin" in the output... :-)

I just tested and that's not what I see when building the sample demo.
