### ISSUE TITLE
Questions about the interface

### ISSUE THREAD

**Issue by rjobling** [arnaud-carre/ldos#5]
Hi Leonard

I'm taking a look at LDOS and I have a few hopefully simple questions:

It seems like there is almost no exposed memory allocation other than allocating a share chip ram area between effects. Is that correct? Is it intended that the user will just dc.b all other memory required by the effects and the LDOS system will take care of everything else?

If that's the case then how would you handle shared lookup tables or things like that, or have you just tried to keep it simple by leaving that out?

I'd like to build my effects using Bartman's C environment, it seems plausible that I can generate an exe that'll be stripped down and that I can inline jsr's to LDOS from within C. Do you anticipate any problems I might run into or know of anyone has managed this?

I'm only just getting started, but the system looks awesome, so thanks for sharing!!
Jobbo

**Comment by arnaud-carre** [comment]
Hi! early version of LDOS had dynamic memory alloc public func. But after a while I removed that feature on purpose. Best way to allocate memory in a demo part is to use bss section.
If you want to "re-use" some memory within an executable, best option is to use bss section and all your parts could use the same memory location.

I never used any C compiler on amiga, but I guess calling LDOS from C is possible. As arguments should be passed into registers, you have to look at your C compiler documentation to get register args syntax

Enjoy LDOS!

**Comment by rjobling** [comment]
I was mostly wondering how separate exe's would share memory. For example if two effects both use the same table but you only want to compute it once at the start of the first effect.

Seems like you offer that for chip-ram, maybe a separate other-ram equivalent function could allow for that.

I see: LDOS_MEM_ANY_RAM and LDOS_MEM_CLEAR are in kernel.inc

Are those used for anything right now?

Anyway I can always make my own changes and potentially submit them for review, but obviously good to know about your prior decisions.

**Comment by arnaud-carre** [comment]
right now you can't alloc memory in one exe dans use it in the next exe. Apart from one chip memory, if you really want to keep some gfx on screen between two exe. But, my advice is to chain exe with just no memory in between, just keeping a blank screen. If blank screen is few frame, it's not an issue for a demo. Many demos with great chaining effect between parts have blank screen of few frames between parts.
For instance The Fall and De Profundis are made like that.

**Comment by rjobling** [comment]
That's very reasonable, and those demos are amazing!

However, I have some circumstances where I'd ideally like more flexibility with memory usage.

I have an effect that needs almost all the ram. What's worse I'm using HAM5 which isn't compatible on AGA. So, on AGA I need to allocated a little extra chip ram so I can put in a 6th bitplane that isn't needed and doesn't fit on OCS.

I'd also like to be able to free up some of that memory toward the end of the effect so there's room to start loading in the next effect.

I only had a glance at your allocator and don't really know how it works. But for my purposes I think it would work well if the allocation used a stack allocating from the bottom for the current effect and from the top for the next effect. I could even imagine a scheme where one effect leaves some of it's allocations on the stack for hand off to the next. Chip ram and other ram would need separate stacks.

I might try doing something like that myself but maybe it's completely incompatible with how LDOS works? If you could give me a quick summary of how the allocation does work and what restrictions it's having to deal with that'd give me a head start when looking over the code.

Thanks for any help and suggestions.

**Comment by arnaud-carre** [comment]
LDOS allocator is really simple, it uses only pages of 4KiB. Each page is using one byte saying "free" ( 0 ) or "busy" (other than 0). This byte is called "label" so for instance if you could alloc 100KiB using label "$31" and it's persistent. The system become complex to avoid memory fragmentation, that's why LDOS free everything right before running the next part ( because LDOS is depacking while loading next part).
So sum up, yes it's doable to use your own memory allocator, but it's tricky to make it work with the loading&depacking system

**Comment by rjobling** [comment]
Thanks, for now it seem like more than I'd like to tackle. But I did get a C effect working with the system by implementing an inline version of the interface. So that was nice to see working!

**Comment by rjobling** [comment]
This is old and I moved on  :)
