### ISSUE TITLE
"This demo requires 1MiB of RAM" error is corrupted.

### ISSUE THREAD

**Issue by ghost** [arnaud-carre/ldos#6]
![image](https://user-images.githubusercontent.com/65902926/228798369-4be23f01-47ad-49c2-b7cc-5c57f292fa12.png)

Maybe the lower case letters are missing?

Also, it's not clear from the documentation whether clear whether this check can be disabled and LDOS can be used for 512K demos?

**Comment by arnaud-carre** [comment]
that is not expected. What Amiga configuration are you using to repro this behavior?
